version: "3"
services:
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:4.0.2
    restart: always
    environment:
      MONGO_INITDB_DATABASE: explorer
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
