name: 042 Trigger DevNet Block Explorer Build And Deploy Pipeline
on:
  push:
    branches:
      - 'feature/0.42'
#triger
jobs:
  DevNet:
    name: Trigger Block Explorer Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set version
        run: |
          VER=$(cat versions/version)
          echo $VER
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: 042 DevNet Trigger Block Explorer Pipeline
        if: ${{ github.ref == 'refs/heads/feature/0.42' }}
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.CHAINOPS_ACCESS_TOKEN }}
          repo: chainOps
          owner: Sifchain
          event_type: build_bigdipper_042
          message: |
            {
              "aws_region": "us-east-1",
              "target_big_dipper_branch": "feature/0.42",
              "app_region": "us",
              "aws_cluster_name": "sifchain-aws-devnet-042-data",
              "aws_role": "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole",
              "app_namespace": "block-explorer",
              "image": "sifchain/block-explorer",
              "image_tag": "devnet-${{ env.VERSION }}",
              "version": "${{ env.VERSION }}",
              "env": "data",
              "app_name": "block-explorer",
              "app_env": "data"
            }
