name: Trigger DevNet Block Explorer Build And Deploy Pipeline
on:
  push:
    branches:
      - 'develop'
      - 'testnet'
      - 'master'
      - 'adding-trigger-pipeline'
jobs:
  DevNet:
    name: Trigger Block Explorer Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Set version devnet
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          VER=$(cat versions/devnet/version)
          echo $VER
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Set version dding-trigger-pipeline
        if: ${{ github.ref == 'refs/heads/adding-trigger-pipeline' }}
        run: |
          ls -lah
          VER=$(cat versions/devnet/version)
          echo $VER
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Set version testnet
        if: ${{ github.ref == 'refs/heads/testnet' }}
        run: |
          VER=$(cat versions/devnet/version)
          echo $VER
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: DevNet Trigger Block Explorer Pipeline
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: mvasigh/dispatch-action@main
        with:
          # You should create a personal access token and store it in your repository
          token: ${{ secrets.CHAINOPS_ACCESS_TOKEN }}
          repo: chainOps
          owner: Sifchain
          event_type: build_bigdipper
          message: |
            {
              "aws_region": "us-east-2",
              "target_big_dipper_branch": "develop",
              "app_region": "us",
              "aws_cluster_name": "sifchain-aws-devnet-data",
              "aws_role": "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole",
              "app_namespace": "block-explorer",
              "image": "sifchain/block-explorer",
              "image_tag": "${{ env.VERSION }}",
              "env": "data",
              "app_name": "block-explorer",
              "app_env": "data"
            }

      - name: adding-trigger-pipeline Trigger Block Explorer Pipeline
        if: ${{ github.ref == 'refs/heads/adding-trigger-pipeline' }}
        uses: mvasigh/dispatch-action@main
        with:
          # You should create a personal access token and store it in your repository
          token: ${{ secrets.CHAINOPS_ACCESS_TOKEN }}
          repo: chainOps
          owner: Sifchain
          event_type: build_bigdipper
          message: |
            {
              "aws_region": "us-east-2",
              "target_big_dipper_branch": "develop",
              "app_region": "us",
              "aws_cluster_name": "sifchain-aws-devnet-data",
              "aws_role": "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole",
              "app_namespace": "block-explorer",
              "image": "sifchain/block-explorer",
              "image_tag": "${{ env.VERSION }}",
              "env": "data",
              "app_name": "block-explorer",
              "app_env": "data"
            }

      - name: TestNet Trigger Block Explorer Pipeline
        if: ${{ github.ref == 'refs/heads/testnet' }}
        uses: mvasigh/dispatch-action@main
        with:
          # You should create a personal access token and store it in your repository
          token: ${{ secrets.CHAINOPS_ACCESS_TOKEN }}
          repo: chainOps
          owner: Sifchain
          event_type: build_bigdipper
          message: |
            {
              "aws_region": "us-east-2",
              "target_big_dipper_branch": "testnet",
              "app_region": "us",
              "aws_cluster_name": "sifchain-aws-testnet-data",
              "aws_role": "arn:aws:iam::346064283538:role/OrganizationAccountAccessRole",
              "app_namespace": "block-explorer",
              "image": "sifchain/block-explorer",
              "image_tag": "${{ env.VERSION }}",
              "env": "data",
              "app_name": "block-explorer",
              "app_env": "data"
            }